### ISSUE TITLE
[Proposal] Log wrapper

### ISSUE THREAD

**Issue by mtthw-meyer** [stm32-rs/stm32h7xx-hal#104]
For my own project I wrapped the log crate to allow output via RTT or none via feature. A feature gated logger implementing several implementations sounds really useful. Could include ITM, RTT, etc. Leaving no features selected makes the macro empty and it get's compiled out.

Is this the right level of crate for this or should it go somewhere else?

[Example](https://gist.github.com/mtthw-meyer/0c1d4977cfbb848916f92830c35c852c)

**Comment by richardeoin** [comment]
It sounds like RTT support (and other debugging methods) have improved recently, although there's still some potential pitfalls, eg. the bug in the commonly-used OpenOCD that breaks ITM.

Your proposal sounds great, with optional feature gates then I think it's fine to have here. Even better if we can use it consistently for all the examples, and provide some docs for new users. Then it would close #7
