### ISSUE TITLE
embedded hal digital IO v2

### ISSUE THREAD

**Issue by hargoniX** [stm32-rs/stm32h7xx-hal#11]
The embedded hal group marked the v1 of digital IO as deprecated, should we also implement a v2 version for the future already?

**Comment by richardeoin** [comment]
We're already there!

* [Implementation](https://github.com/stm32-rs/stm32h7xx-hal/blob/1a217f42ed149ed9211f621dc93df8ac7bf26c21/src/gpio.rs#L111)
* [Example](https://github.com/stm32-rs/stm32h7xx-hal/blob/1a217f42ed149ed9211f621dc93df8ac7bf26c21/examples/blinky.rs#L10)
