### ISSUE TITLE
Cargo.toml typo

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32h7xx-hal#131]
In Cargo.toml  I think the line 
`stm32h742 = ["stm32h7/stm32h743", "device-selected", "singlecore"]`
should have `742` in place of `743`

**Comment by richardeoin** [comment]
Thanks for reporting!

This line uses the `stm32h743` feature flag from the [stm32-rs PAC](https://docs.rs/stm32h7/latest/stm32h7/). The PAC doesn't distinguish between the 742 and 743 as they have (almost?) the same registers.

If you're using the stm32h742 and find significant differences, you can report register differences in stm32-rs and feature differences (clock speeds, peripheral features,..) here.
