### ISSUE TITLE
Example for I2c Interrupts

### ISSUE THREAD

**Issue by ostenning** [stm32-rs/stm32h7xx-hal#181]
Hello,

I'm trying to figure out how to use I2C interrupts (master tx). I see that the driver supports listening for interrupts, but there is no clear example of how to use it.

Thanks for the assistance

Kind regards,
Oliver

**Comment by mattico** [comment]
I haven't used I2C interrupts before but it should be similar to any other interrupts.

1. Configure I2C. Call `listen()` to enable raising interrupts for the desired event(s).
2. Create an interrupt handler. This can be done using [the macro](https://docs.rs/stm32h7xx-hal/0.8.0/stm32h7xx_hal/attr.interrupt.html)
   https://github.com/stm32-rs/stm32h7xx-hal/blob/f3e10a1e3b61832261aaa10db0443c5911aa6d29/examples/exti_interrupt.rs#L117-L129
   Or [by using RTIC](https://rtic.rs/0.5/book/en/by-example/app.html#hardware-tasks)
   https://github.com/stm32-rs/stm32h7xx-hal/blob/f3e10a1e3b61832261aaa10db0443c5911aa6d29/examples/rtic.rs#L54-L58
3. If you're not using RTIC, you then need to enable the interrupts in the interrupt controller
    https://github.com/stm32-rs/stm32h7xx-hal/blob/f3e10a1e3b61832261aaa10db0443c5911aa6d29/examples/exti_interrupt.rs#L79-L84

I'd recommend reading the reference manual for your chip to understand when each interrupt is raised, and if any specific configuration is required. I don't think anything special is needed for I2C, though.

If you run into any issues, leave a comment! It'll help when making an I2C interrupt example.

**Comment by richardeoin** [comment]
Hi! As well at those tips from mattico, you can also have a look at the I2C BDMA example on the dma branch https://github.com/stm32-rs/stm32h7xx-hal/blob/dma/examples/i2c4_bdma.rs 
It only works with I2C4 (because it's the Basic DMA), but the interrupt part applies to all the I2Cs)

**Comment by ostenning** [comment]
Thanks for the responses! @richardeoin that DMA branch looks really awesome. If I2C DMA has already been implemented, I'll see if I can get that working with my application

**Comment by richardeoin** [comment]
Closing as the i2c4_bdma example is now merged and [shows i2c interrupt usage](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/examples/i2c4_bdma.rs#L72-L76).
