### ISSUE TITLE
Build failes with features = [ "stm32h743", "smps" ]

### ISSUE THREAD

**Issue by daniel-dbg-ginsburg** [stm32-rs/stm32h7xx-hal#217]
When configured for [ "stm32h743", "smps" ], compilation fails with:
error[E0599]: no method named `sden` found for struct `stm32h7::R<u32, Reg<u32, stm32h7::stm32h743::pwr::_CR3>>` in the current scope
   --> /home/dbg/.cargo/registry/src/github.com-1ecc6299db9ec823/stm32h7xx-hal-0.9.0/src/pwr.rs:176:44
    |
176 |                 assert!(self.rb.cr3.read().sden().bit_is_clear(), error);
    |                                            ^^^^ method not found in `stm32h7::R<u32, Reg<u32, stm32h7::stm32h743::pwr::_CR3>>`

Versions: 
stm32h7xx-hal v0.9.0
stm32h7 v0.13.0

The reason for the failure is that the PWR_CR3 in stm32h743 does not have the SDEN bit.

**Comment by mattico** [comment]
I can't find any STM32H743 models that include an SMPS. Which chip are you using?

**Comment by daniel-dbg-ginsburg** [comment]
I apologize, I didn't make my point clear. Compilation should fail with a more meaningful message than a bunch of errors about a non-existing flag in a configuration register.

**Comment by richardeoin** [comment]
It is indeed impossible to hit this with any H7 product from ST, but fixed anyhow for completeness
