### ISSUE TITLE
Ethernet interrupts can cause application hanging

### ISSUE THREAD

**Issue by ryan-summers** [stm32-rs/stm32h7xx-hal#275]
# Summary
There is a by-default-on interrupt in the Ethernet MAC (MMC) that occurs after a specific number of packets have been sent. If the ethernet ISR is enabled when this interrupt occurs, the ethernet ISR will hang, as the status flag is never cleared.

# Background
The Ethernet MAC MMC contains a number of counters that count MAC-related statistics like the number of ethernet frames sent. When these counters reach 1/2 full (2^31 packets) and full (2^32 packets), an interrupt flag is set.

There is a mask register to disable these counter interrupts, but the mask is reset-0, which means these interrupts are **not** masked by default (thus, they are enabled).

The failure mode here is that an application can appear to hang up after a number of days of heavy ethernet traffic.

Refer to https://github.com/quartiq/stabilizer/issues/450 for further information.

**Comment by ryan-summers** [comment]
I believe we need to mask away MMC RX/TX interrupts in the `ETH_MMC_TX_INTERRUPT_MASK` and `ETH_MMC_RX_INTERRUPT_MASK` registers. These interrupts are unmasked by default.

**Comment by jordens** [comment]
@ryan-summers @richardeoin can we squeeze [the fix for this](https://github.com/quartiq/stabilizer/pull/462/files) into v0.11.0?

**Comment by richardeoin** [comment]
@jordens Agreed! PR above
