### ISSUE TITLE
[Feature Request] FLASH implementation

### ISSUE THREAD

**Issue by ostenning** [stm32-rs/stm32h7xx-hal#281]
A FLASH implementation that allows for unlocking flash and overwriting it would be great for those wanting to write custom bootloaders for their apps

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/stm32-hal/blob/main/src/flash.rs

Supports H7. Ignore the irrelevant feature flags.

**Comment by ostenning** [comment]
Thanks @David-OConnor, that helped me get started with it.

https://github.com/stm32-rs/stm32h7xx-hal/pull/322
