### ISSUE TITLE
Documentation/comments need to be updated to indicate support for vos0

### ISSUE THREAD

**Issue by timblakely** [stm32-rs/stm32h7xx-hal#326]
Thanks for the HAL, this makes migrating from the G4 to the H7 _so_ much less painful!

It appears that between #96  and #120  now have support for `vos0`, which is particularly helpful to help the STM32H7(2x|3x) series hit 550MHz (!). The documentation for `pwr.rs` suggests that "The voltage scaling mode is fixed at VOS1", which AFAICT is no longer the case given `examples/vos0.rs`, specifically `let pwrcfg = example_power!(pwr).vos0(&dp.SYSCFG).freeze();`. Still working on confirming that this does allow me to hit 550MHz on the NUCLEO-H723, but all signs point to "probably yes".

**Comment by richardeoin** [comment]
That's a good point, the documentation is indeed outdated after those PRs. With https://github.com/stm32-rs/stm32h7xx-hal/pull/316 (now on the master branch) I have tested the H725/735 parts at 520MHz!
