### ISSUE TITLE
ADC example scaling wrong

### ISSUE THREAD

**Issue by jordens** [stm32-rs/stm32h7xx-hal#343]
The ADC examples scale the ADC codes with `VREF/max_sample`.

https://github.com/stm32-rs/stm32h7xx-hal/blob/a46841c4465978aeddef3795b4f571c6c25cfcc9/examples/adc.rs#L76-L80

`max_sample = ((1 << bits) - 1) << lshift` by itself is correct according to its docstring. 

https://github.com/stm32-rs/stm32h7xx-hal/blob/a46841c4465978aeddef3795b4f571c6c25cfcc9/src/adc.rs#L790-L793

But the conversion is not. VREF corresponds to `1 << bits + lshift` here as in all ADCs that I know of.
c.f. https://github.com/stm32-rs/stm32f4xx-hal/issues/362#issuecomment-941014100 and other places.

The best approach is probably to change `max_sample()` and its docstring.

**Comment by richardeoin** [comment]
I enjoyed the explaination on the f4 thread, thanks! Indeed this is clearly an error in the example, and a footgun in the API.

My preferred way of fixing this would be to add a new method, perhaps `pub fn slope(&self) -> u32` that returns `1 << bits + lshift`. After that, `max_sample` can be marked as depreciated.

**Comment by jordens** [comment]
Yes. Much better solution!
