### ISSUE TITLE
Question : Configure Rx FIFO trigger for Usart Serial

### ISSUE THREAD

**Issue by yann77500** [stm32-rs/stm32h7xx-hal#348]
I begin in Rust,
I can't found how configure Rx fifo for serial on usart.
When I start listen() on RxEvent, it seems interrupt every byte received. 
Is it possible to configure Rx Fifo trigger ?

Thank you for your reply

**Comment by mattico** [comment]
The FIFO level is not currently configurable with the HAL.

It should be easy to add similar to: https://github.com/stm32-rs/stm32h7xx-hal/pull/340/files#diff-fb3a60b3de1be206f6d00d6331d24886f8e145d6091d8d4b4557247b8017bd82

**Comment by yann77500** [comment]
Thank you for your reply, 
I will try to study for add the feature

**Comment by richardeoin** [comment]
Closed by #350
