### ISSUE TITLE
Possibility to reset clocks

### ISSUE THREAD

**Issue by ostenning** [stm32-rs/stm32h7xx-hal#363]
After the `rcc` is frozen, It doesn't seem possible to reset the clocks back to their original state.

Is this a possibility?

My use case is that I would like to have a bootloader configure clocks that are independent from the main application clocks.
I would like to reset the bootloader clocks just before the application boots.

Kind regards

**Comment by richardeoin** [comment]
There's no function to reset the clocks in the HAL. However it's relatively easy to do in your own code if necessary - something like this should work:

```rust
unsafe {
    // Switch the system clock back to HSI (default)
    let rcc = &*stm32h7xx_hal::stm32::RCC::ptr();
    let swbits = 0; // HSI
    rcc.cfgr.modify(|_, w| w.sw().bits(swbits));
    while rcc.cfgr.read().sws().bits() != swbits {}

    // And disable all the PLLs
    rcc.cr
        .modify(|_, w| w.pll1on().off().pll2on().off().pll3on().off());
}
```
