### ISSUE TITLE
Can no longer write to flash

### ISSUE THREAD

**Issue by ostenning** [stm32-rs/stm32h7xx-hal#373]
Upon upgrading to the HEAD [commit](https://github.com/stm32-rs/stm32h7xx-hal/commit/6698c1f423ef40d6eb8697b774ad923858d23e8a), my bootloader application can no longer write to the flash. This issue seems to be introduced after tag `0.12.2`.

@richardeoin  @lachlansneff-parallel I see there were some changes made, can you please double check that they are okay?

Kind regards,
Oliver

**Comment by lachlansneff-parallel** [comment]
Almost certain this was my fault. I've also been having issues. #371 fixes this for certain though!

**Comment by richardeoin** [comment]
@ostenning Thanks for reporting! Could you test with the latest HEAD now that https://github.com/stm32-rs/stm32h7xx-hal/pull/371 is merged please?

**Comment by ostenning** [comment]
@richardeoin @lachlansneff-parallel  Good news, from my testing it looks like things are working nicely. I've had my bootloader looping continually reflashing the stm32 for the past few hours and its been working fine
