### ISSUE TITLE
STM32H743 Clock speed

### ISSUE THREAD

**Issue by jg2562** [stm32-rs/stm32h7xx-hal#399]
The stm32h743 panicks when the sys_ck is set to 480MHz. 400MHz is the lowest non-panicking value.I believe the h743 is advertised to run at 480MHz, is this a limitation of the hardware or of the library?

**Comment by mattico** [comment]
Have you enabled the cargo feature `stm32h743v`. Note the **v**.

**Comment by jg2562** [comment]
It was definitely the v, thank you!
