### ISSUE TITLE
fdcan not building 

### ISSUE THREAD

**Issue by FranciscoAmaro24** [stm32-rs/stm32h7xx-hal#465]
Im trying to implement fdcan on my stm32h743 nucleo but i cannot get the fdcan crate to build nor be recognized by the compiler when imported like "use fdcan..."

**Comment by richardeoin** [comment]
Hi Francisco. As well as including `stm32h7xx-hal` in the Cargo.toml `[dependencies]` of your project, you also need to include `fdcan = "0.2"`
