### ISSUE TITLE
Problems with timer clocks

### ISSUE THREAD

**Issue by MStarha** [stm32-rs/stm32h7xx-hal#478]
I want to get the configred clocks for timer TIM2 on my stm32h743vgt6. This `let clk = ccdr.peripheral.TIM2::get_clk(&ccdr.clocks).unwrap().raw();` produces an error:
```
error: expected `<`
   --> src/main.rs:176:41
    |
176 |         let clk = ccdr.peripheral.TIM2::get_clk(&ccdr.clocks).unwrap().raw();
    |                                         ^^^^^^^
```
I do have the use `stm32h7xx_hal::timer::GetClk` trait in scope. What is the problem?

**Comment by richardeoin** [comment]
[Associated functions must be called on the type itself, not an instance of the type](https://doc.rust-lang.org/rust-by-example/fn/methods.html)
