### ISSUE TITLE
Local copy of latest stm32-rs required to build

### ISSUE THREAD

**Issue by richardeoin** [stm32-rs/stm32h7xx-hal#5]
Waiting on an [upstream](https://github.com/stm32-rs/stm32-rs) release.

**Comment by jordens** [comment]
@richardeoin @astraw @hargoniX do you have pending breaking changes for stm32-rs that you would like to land before 0.8 or can we try pushing for that release to get this out of the way? I don't have anything pending for 0.8.

**Comment by hargoniX** [comment]
I don't have done anything related to stm32-rs yet so that's a clear no from me

**Comment by astraw** [comment]
Also nothing pending from me.

**Comment by richardeoin** [comment]
@jordens I've got two PRs open

https://github.com/stm32-rs/stm32-rs/pull/241
https://github.com/stm32-rs/stm32-rs/pull/246

Would be good to land them for 0.8
