### ISSUE TITLE
SPI operates in "endless transaction" mode

### ISSUE THREAD

**Issue by ryan-summers** [stm32-rs/stm32h7xx-hal#71]
When a SPI transaction occurs, the HAL operates the SPI in "endless transaction" mode, which means that the SPI peripheral is not able to detect when a transaction completes.

The SPI_CR2.TSIZE register value needs to be updated with the size of the transaction in bytes before a transaction is initiated.

**Comment by richardeoin** [comment]
This behaviour seems to be OK for simple SPI usage, but fixing this would be an improvement 👍
