### ISSUE TITLE
Prec structures preclude using ADC1 and ADC2 simultaneously 

### ISSUE THREAD

**Issue by ryan-summers** [stm32-rs/stm32h7xx-hal#93]
The existing Prec implementation precludes using ADC1 and ADC2 simultaneously because only a single Prec structure is generated for both ADC implementations.

**Comment by ryan-summers** [comment]
@richardeoin Perhaps we could update the ADC constructor to just borrow the ADC PREC structure, which would allow it to be used more than once? Curious to hear your thoughts. We could potentially also generate duplicate PREC structures for ADC1 and ADC2, but I feel like that would obfuscate the fact that they're essentially sharing resources.

**Comment by richardeoin** [comment]
I think this is the only case where a single reset line is used to control two peripherals that have separate definitions in the SVD.

We could fix this the in ADC HAL by initialising both ADC1 and ADC2 at the same time. The usage would then look like:

```
Adc::adc12(dp.ADC1, dp.ADC2, ccdr..., ...) -> (adc1, adc2)
```

**Comment by richardeoin** [comment]
So if you were just using ADC1:

```
let (adc1, _) = Adc::adc12(dp.ADC1, dp.ADC2, ccdr..., ...);

**Comment by ryan-summers** [comment]
I like that concept as it makes it very clear to the user that the peripherals are intertwined.

**Comment by richardeoin** [comment]
Indeed, it forces any alternative ADC HAL implementations to acknowledge that ADC1 and ADC2 are linked

**Comment by ryan-summers** [comment]
I'd be happy to write up a PR for this change. It'd be nice to get some of the `stabilizer` code base as back-on-track with the HAL as possible.

**Comment by richardeoin** [comment]
I'm most of the way through making the change, will push a PR shortly. I'll open the branch to collaborators though, if there's anything you want to add.

**Comment by ryan-summers** [comment]
Fixed in https://github.com/stm32-rs/stm32h7xx-hal/pull/94
