### ISSUE TITLE
Add PLL strategy for fractional clock

### ISSUE THREAD

**Issue by mtthw-meyer** [stm32-rs/stm32h7xx-hal#98]
The fractional divisor allows setting of precise clocks during runtime using the rcc_pllxfracr register. It needs to be enabled during startup. I purpose adding two new PLL strategies that enable the fractional divisor. One for just below and just above a target value. (e.g. for audio I want a clock that is as close to possible as 48 KHz * 256 without going _under_).

I think the existing iterative strategy could be used to set the base clock and then tweak the rcc_pllxfracr from there.

PllConfigStrategy::FractionalGreaterThan
PllConfigStrategy::FractionalLessThan

**Comment by richardeoin** [comment]
Sound like a reasonable plan to me. Since the existing PLL strategies set frequencies that are less than or equal to specified, a "less than or equal to" strategy could just be: `PllConfigStrategy::Fractional` for consistency.
